language: node_js
sudo: false
node_js:
  - "10"
before_install:
  - npm install -g codecov
install:
  - npm install
jobs:
  include:
    - stage: Test with Mocha
      script:
        - npm test
    - stage: Report Code Coverage
      script:
        - npm run coverage